//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MensajeriaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactos
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string organizacion { get; set; }
        public string puesto { get; set; }
        public string archivar_como_a { get; set; }
        public string email { get; set; }
        public string mostrar_como { get; set; }
        public string pagina_web { get; set; }
        public string direccion_im { get; set; }
        public string tel_trabajo { get; set; }
        public string tel_particular { get; set; }
        public string fax_trabajo { get; set; }
        public string tel_movil { get; set; }
        public string direccion_trabajo { get; set; }
        public Nullable<int> direccion_correspondencia { get; set; }
        public string notas { get; set; }
        public string imagen { get; set; }
    }
}
